" Include default global config
" source /etc/vimrc

" 1,000 lines for copy buffer
set viminfo='20,<1000,s1000

" Reminder last line in file
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

" Disable arrow keys
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>
